<?php
if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_site-text',
        'title' => 'Site Text',
        'fields' => array(
            array(
                'key' => 'field_529545626aad6',
                'label' => 'Site Tag Line',
                'name' => 'site_tag_line',
                'type' => 'text',
                'default_value' => 'Meet the people renewing America',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529546c06aad7',
                'label' => 'Facebook Button Expanded Text',
                'name' => 'facebook_button_expanded_text',
                'type' => 'text',
                'default_value' => 'Follow on Facebook',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529546e76aad8',
                'label' => 'Twitter Button Expanded Text',
                'name' => 'twitter_button_expanded_text',
                'type' => 'text',
                'default_value' => 'Follow on Twitter',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529547866aad9',
                'label' => 'Twitter Button Bingo Text',
                'name' => 'twitter_button_bingo_text',
                'type' => 'text',
                'default_value' => 'Tweet',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529547b26aada',
                'label' => 'Facebook Button Bingo Text',
                'name' => 'facebook_button_bingo_text',
                'type' => 'text',
                'default_value' => 'Share',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529548196aadb',
                'label' => 'Take Action Header Text',
                'name' => 'take_action_header_text',
                'type' => 'text',
                'default_value' => 'Take Action',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5295483b6aadc',
                'label' => 'More Stories Heading Prefix',
                'name' => 'more_stories_heading_prefix',
                'type' => 'text',
                'default_value' => 'More Stories in',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5295486c6aadd',
                'label' => 'Load More Button Text',
                'name' => 'load_more_button_text',
                'type' => 'text',
                'default_value' => 'Load More',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529548896aade',
                'label' => 'Nav Search Placeholder Text',
                'name' => 'nav_search_placeholder_text',
                'type' => 'text',
                'default_value' => 'Search NationSwell',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5295490b6aadf',
                'label' => 'Nav Subscribe Placeholder Text',
                'name' => 'nav_subscribe_placeholder_text',
                'type' => 'text',
                'default_value' => 'Subscribe to NationSwell daily',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_529549396aae0',
                'label' => 'Byline Prefix Text',
                'name' => 'byline_prefix_text',
                'type' => 'text',
                'default_value' => 'by',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
}
